version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - COUNTER_FILE="requests.csv"
      - MAX_PARALLEL_REQUESTS=5
    volumes:
      - counter-data:/app

volumes:
  counter-data: